language: python
python:
- 3.8
env:
- TOXENV=django22
- TOXENV=quality
- TOXENV=pii-annotations
matrix:
  include:
  - python: 3.8
    env: TOXENV=django30
cache:
- pip
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements/travis.txt
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.8
    condition: "$TOXENV = quality"
  password:
    secure: B5kIZ0CYgJ9NmlXH7CcGDE2Ytvklx5XBh2Unvd1/ElJJnvvH6vLxnHFbmNqshp9iNhSNPEOuviUTz+072YRdGbLgVGbCJibtZFD1lTwZEsAW+ciKgL19+BAB4osQdHJImTeKLeDoOPGQ3tnIPxBM3ZdLxttTB3J4kS0wRoZcgelac9brnXtQErEBxeFNNfDLP/yRjH5umvCEBAg4oKwvlO3wFmyYbCNmy4vPvsQuHNyJimTkNYQTf2sSb6JySrSMDvSyW0TdjJ6AhOI4LSbMqQHAHmFty18XgBnE/72rnWJjn/XG/vPsWTDTArNUCbYB6Q5Kbhr37mYytxeGf1DVjXzP/N5wySZ0Gdob2QgOdRub4KA4D+OfSGXeF6SfgMA0jZlEKxbW9CGKSbL7LN+XK2/D5TGpbgE/xmXq96LqM+QPt9zNvmbf+1aHRmUSynIS7FU5BHwetJL+yul908BSucNLGFzq6DDV7NOEirEiwpRfYBgs4FSUQg8hRXsucZUZlyihIInpu/jx6Co/RoR94KJKBdQlsZnsFLT9GZz9gLJefX/6XH83mWdCUNdUb8wgFpf3tYnb0BIRpD5GxDbvq62BmixF2J5DK0KQd9/Zcjv0CiJgNg4UqQ5sig2pb2Av530uqVijsB3O5gc7Q+MwxWtCRZWPHT+I9PtJMYsoSA0=
